### ISSUE TITLE
Afstand naar afspraak

### ISSUE THREAD

**Issue by Dimitry24** [Koozza/StudentAanHuis-Android#16]
Als je meerdere werkgebieden hebt, dan selecteer de laatst gekozen werkgebied om afstanden te bepalen, die moet handiger kunnen of instelbaar of aanpasbaar kunnen zijn. Het liefst dat hij automatisch het dichts bijzijnde werk gebied kiest en dan de afstand bepaald.

**Comment by Koozza** [comment]
Solved in 1.1.1
