### ISSUE TITLE
Geen menuknop op telefoons zonder hardwarematige knop

### ISSUE THREAD

**Issue by RemcoKorevaar** [Koozza/StudentAanHuis-Android#6]
Op telefoons zonder hardware opties/menu knop (OnePlus One, Nexus toestellen) zijn de mogelijkheden om prikbord/werkgebied te herladen niet te bereiken. Wellicht een idee om dit te implementeren door de design guidelines van Android aan te houden.

**Comment by Koozza** [comment]
Ik wist niet dat er telefoons waren die die knop niet hadden 0.o Dacht dat deze altijd wel softwarematig benaderbaar waren. Voor nu zet ik die toch even op won't fix, omdat dit later sowiso naar een andere plaats gaat :)

**Comment by RemcoKorevaar** [comment]
Die knop wilt Google eigenlijk uitfaseren vanaf Android 4.2 ofzo. De knop zou bij mij automatisch zichtbaar moeten worden op mijn scherm als de mogelijkheid er is (a.k.a. "oude" apps die deze knop nog gebruiken). Dit gebeurt echter niet bij mij.

**Comment by Koozza** [comment]
Ok, waar willen ze het dan heen gaan doen? Want die balk bovenin heb ik juist expres weggehaald :P Maar ik denk dat het sowiso naar een andere plek gaat, dus ik denk dat ik daar nu niet heel veel tijd in steek.

Je werkgebieden hoef je over het algemeen niet te refreshen, en de prikbord items reloaden elke keer dat je de app opstart :)

**Comment by RemcoKorevaar** [comment]
Dat scheelt gelukkig wel. Uitleg van Material Design en ander uitleg van ontwerp op Android staat op http://developer.android.com/design/material/index.html

**Comment by Koozza** [comment]
Ja precies, ik dacht al dat het die balk was :P Komt later nog goed :) Die opties waren meer als "Redmiddel" ingebouwd voor als er iets mis ging met de interne database, het is meer richting database leeggooien en alles opnieuw ophalen.
